### ISSUE TITLE
(v2) Inconsistent toBytes / fromBytes behaviour

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-sdk-js#297]
(with sdk v2.0.0 - master branch today)

```
    const transferTransaction = new TransferTransaction()
        .addHbarTransfer(receipt.accountId, -1)
        .addHbarTransfer("0.0.3", 1)
        .freezeWith(client);

    const transactionBytes = transferTransaction.toBytes();
    const transactionToExecute = Transaction.fromBytes(transactionBytes);
```

results in `error while decoding: Error: invalid wire type 4 at offset 11`

while (_note added setMaxTransactionFee_)

```
    const transferTransaction = new TransferTransaction()
        .setMaxTransactionFee(10)
        .addHbarTransfer(receipt.accountId, -1)
        .addHbarTransfer("0.0.3", 1)
        .freezeWith(client);

    const transactionBytes = transferTransaction.toBytes();
    const transactionToExecute = Transaction.fromBytes(transactionBytes);
```

results in `error while decoding: RangeError: index out of range: 173 + 10 > 173`

**Comment by danielakhterov** [comment]
This should now be fixed in v2.0.1 release, re-open if issue persists.

**Comment by gregscullard** [comment]
The `index out of range` issue is closed, however I'm still getting `invalid wire type` followed by `No transaction found in bytes`
This is the code I'm using to test

```
    const transferTransaction = new TransferTransaction()
        .addHbarTransfer(receipt.accountId, -1)
        .addHbarTransfer("0.0.3", 1)
        .freezeWith(client);

    // convert transaction to bytes to send to signatories
    const transactionBytes = transferTransaction.toBytes();
    const transactionToExecute = Transaction.fromBytes(transactionBytes);
```

**Comment by gregscullard** [comment]
@abonander

**Comment by danielakhterov** [comment]
@gregscullard 
The test I had used only a single node `AccountId` which is why I thought I had fixed `Transaction.[from|to]Bytes()`.
I don't know why this hadn't come to me sooner, but I completely changed the way those methods are handled to use a new protobuf type called `TransactionList`. By using this new protobuf type it should hopefully eliminate any further issues as we no longer try to parse bytes ourselves. Another benefit of this type is that it will make it much easier to encode/decode bytes from other SDK's _when they implement this type_. I have released v2.0.3, and added a test which sets multiple node `AccountId`. Can you please test your transaction again.

**Comment by gregscullard** [comment]
@danielakhterov this works if I set the node account ids
```
    const transferTransaction = new TransferTransaction()
        .setNodeAccountIds([new AccountId(3)])
        .addHbarTransfer(receipt.accountId, -1)
        .addHbarTransfer("0.0.3", 1)
        .freezeWith(client);
```

I would expect that `.freezeWith` would set a random account Id so that it's transparent. Setting a node/nodes is appreciated as a feature, but it should be optional in all cases and a developer choice to use the feature or not.

The below still fails (_note, no `.setNodeAccountIds`_)
```
    const transferTransaction = new TransferTransaction()
        .addHbarTransfer(receipt.accountId, -1)
        .addHbarTransfer("0.0.3", 1)
        .freezeWith(client);
```

**Comment by danielakhterov** [comment]
I believe the issue was with how we were serializing transactions that have multiple nodes set. Now that we use the `TransactionList` protobuf type I believe the issue is resolved. I have added a test for multi-node `Transaction.toBytes()` which passes: https://github.com/hashgraph/hedera-sdk-js/blob/master/test/unit/Transaction.js#L10 I'll close this issue as I think it's resolved, but if the issue persists please reopen.
