### ISSUE TITLE
Transactions submitted to UNAVAILABLE nodes are not retried for mainnet

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-sdk-js#345]
js-sdk retry logic isn't as robust as expected and doesn't seem to retry.

For instance when pointing to mainnet (`Client.forMainnet()`) I can issue 10 accountInfo requests.
All 10 seem to fail with `Error: 14 UNAVAILABLE: Connection dropped`

The occurrences are understandable as some nodes may be down, however the expectation is that there would be transaction retries on different nodes to ensure the client submitted transactions made it's way to the network
Java sdk does this quite well, it handles non available nodes but retries on available ones.

version  - `@hashgraph/sdk - ^2.0.17-beta.2`

Code snippers used below
```js
client = Client.forMainnet();
...
accountInfo = await new AccountInfoQuery().setAccountId(accountId).execute(client);
```

**Comment by danielakhterov** [comment]
@Nana-EC Can you retry this with the latest release. Due to some misunderstandings we updated all the mainnet nodes to use port 50212 when we shouldn't which is why they were all returning `UNAVAILABLE`. We've reverted the change, and I think this would solve your issue. I'm closing this issue as I believe it is resolved, but if you continue having trouble please reopen this issue.

**Comment by Nana-EC** [comment]
Issue still happened a few times on the `v2.0.17-beta.3` version.
I updated to `v2.0.17-beta.7` and it happened on 3 calls out of 1700. 
On subsequent runs I haven't hit it again.

In summary I don't believe the issue is totally fixed but it is less prevalent and not longer requires me to find a single working node.
Not sure if there's already functional retry logic like the java sdk but if not that would be useful to help with this.
